#include "visualLB.h"
#include "computeCellValues.h"
#include "LBDefinitions.h"
#include <stdlib.h>
#include <stdio.h>

void writeVtkOutput(const double * const collideField, const int * const flagField, const char * filename, unsigned int t, int xlength) {
    char szFileName[80];
    double density;
    double cell_velocity[3];
    FILE *fp=NULL;
    sprintf(szFileName, "%s.%i.vtk", filename, t);
    fp = fopen( szFileName, "w");
    if( fp == NULL )
    {
        char szBuff[80];
        sprintf( szBuff, "Failed to open %s", szFileName );
        return;
    }

    write_vtkHeader( fp, xlength);
    write_vtkPointCoordinates(fp, xlength, xlength, xlength);

    fprintf(fp,"POINT_DATA %i \n", (xlength+2)*(xlength+2)*(xlength+2) );

    fprintf(fp,"\n");
    fprintf(fp, "VECTORS velocity float\n");
    for(int x=0;x<=xlength+1;x++){
        for(int y=0;y<=xlength+1;y++){
            for(int z=0;z<=xlength+1;z++){
                const double * const currentCell=collideField+Q*(z*totalLengthSq+y*totalLength+x);
                computeDensity(currentCell, &density);
                computeVelocity(currentCell, &density, cell_velocity);
                fprintf(fp, "%f %f %f\n", cell_velocity[0], cell_velocity[1], cell_velocity[2]);
            }
        }
    }
    if(fclose(fp)){
        char szBuff[80];
        sprintf( szBuff, "Failed to close %s", szFileName );
    }
}

void write_vtkHeader( FILE *fp, int xlength){
    if( fp == NULL )
    {
        char szBuff[80];
        sprintf( szBuff, "Null pointer in write_vtkHeader" );
        return;
    }

    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"generated by CFD-lab course output (base on code written by Tobias Neckel) \n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");
    fprintf(fp,"DATASET STRUCTURED_GRID\n");
    fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength+2, xlength+2, xlength+2);
    fprintf(fp,"POINTS %i float\n", (xlength+2)*(xlength+2)*(xlength+2));
    fprintf(fp,"\n");
}

void write_vtkPointCoordinates( FILE *fp, int imax, int jmax, int kmax) {
    double originX = 0.0;
    double originY = 0.0;
    double originZ = 0.0;

    int i = 0;
    int j = 0;
    int k = 0;

    for(i = 0; i < imax+2; i++) {
        for(j = 0; j < jmax+2; j++) {
            for(k = 0; k < kmax+2; k++) {
                fprintf(fp, "%f %f %f \n", originX+i, originY+j, originZ + k);
            }
        }
    }
}

void writeVtkOutputFlags(const double * const collideField, const int * const flagField, const char * filename, unsigned int t, int xlength) {
    char szFileName[80];
    //double density;
    //double cell_velocity[3];
    FILE *fp=NULL;
    sprintf(szFileName, "%sflags.%i.vtk", filename, t);
    fp = fopen( szFileName, "w");
    if( fp == NULL )
    {
        char szBuff[80];
        sprintf( szBuff, "Failed to open %s", szFileName );
        return;
    }

    write_vtkHeader( fp, xlength);
    write_vtkPointCoordinates(fp, xlength, xlength, xlength);

    fprintf(fp,"CELL_DATA %i \n", (xlength+2)*(xlength+2)*(xlength+2));

    fprintf(fp,"\n");
    fprintf(fp, "SCALARS pressure float 1 \n");
    for(int x=0;x<=xlength+1;x++){
        for(int y=0;y<=xlength+1;y++){
            for(int z=0;z<=xlength+1;z++){
                fprintf(fp, "%i \n", flagField[z*totalLengthSq +y*totalLength +x]);
            }
        }
    }
    if(fclose(fp)){
        char szBuff[80];
        sprintf( szBuff, "Failed to close %s", szFileName );
    }
}

